setwd("C:/Users/DELL/Desktop/UCD Fall/Information/class6/HW3")
rm(list=ls())
library(openxlsx)
library(Hmisc)
library(MASS)
library(caret)
library(regclass)
library(ISLR)
library(boot)
library(vcd)
library(pROC)
library (ROCR)

Data2<-read.xlsx("Assignment3HW3_Data.xlsx",3)
summary(Data2)
levels(as.factor(Data2$`Joined?`))
levels(as.factor(Data2$Churned.at.3.months.after.launch.of.the.online.community))
mylogit<-glm(Churned.at.3.months.after.launch.of.the.online.community~`Joined?`+Customer.Age.with.Firm.at.time.of.launching.the.online.community+Average.Spend.Last.3.months.of.Life.with.the.firm,data=Data2,family=binomial(link="logit"))
summary(mylogit)
Confidence=confint(mylogit) 
Confidence
